### ISSUE TITLE
[Discussion] KLAP Protocol

### ISSUE THREAD

**Issue by RaresAil** [petretiandrea/plugp100#131]
Hey, i have a HomeBridge Plugin to allow the control of Tapo Devices from HomeKit, and i have the issue with light bulbs that use KLAP from the latest update, i was looking at your PR for KLAP, but for handshake1 i always get error_code: -1, would you like to give me more info about it like content_type how the payload should be? Thank you 😄

**Comment by RaresAil** [comment]
I managed to find out the issue i was doing 😄

**Comment by petretiandrea** [comment]
Could you provider more info? Like tapo device?

**Comment by RaresAil** [comment]
The device is L530 Hardware 1 Software 1.3.0, and in my code i have like this, the handshake1 is successful, but on the second one i get 400 and Invalid header 

```js
    const localAuthHash = this.sha256(
      Buffer.concat([remoteSeed, localSeed, authHash])
    );

    try {
      const handshake2Result = await this.sessionPost(
        '/handshake2',
        localAuthHash,
        'text',
        this.session!.Cookie
      );

      console.log('Success!', handshake2Result);
    } catch (e: any) {
      console.log('Err', e.response);
    }
```

```js
  private async sessionPost(
    path: string,
    payload: Buffer,
    responseType: ResponseType,
    cookie?: string
  ) {
    return axios.post(`http://${this.ip}/app${path}`, payload, {
      responseType: responseType,
      headers: {
        Accept: 'text/plain',
        'Content-Type': 'application/octet-stream',
        ...(cookie && {
          Cookie: cookie
        })
      },
      httpAgent: new http.Agent({
        keepAlive: true
      })
    });
  }
  ```

**Comment by RaresAil** [comment]
@petretiandrea Yep, i found the issue, instead of sending the auth hash (password email sha256) i was sending the hash that i used to verify the serverHash 😓

**Comment by RaresAil** [comment]
I will close this cause i managed to get it working 😅
