### ISSUE TITLE
Refresh time between updates from Hub

### ISSUE THREAD

**Issue by mtlguy123** [petretiandrea/plugp100#154]
Hi,

great integration you made available to us. Thanks!

My main issue is that I remember agreeing to having the hub update HA every 30 seconds. Problem is, I have sensors that need to turn on lights when a door is open. However, that can take up to, well, 30 seconds! Being a newb, I'm not 100% sure how / where to change that setting, or if that's even something that's ok to do given the amount of times HA and the hub will "handshake".

Any insight will be greatly appreciated!

**Comment by petretiandrea** [comment]
Unfortunately, Tapo devices has no a "live stream" of events, so the polling is the only ways to get it. You can try to reduce the polling time
